fix: correct novalidate attribute rendering in hmpoForm component
W3C HTML Validator raised the following issue

```
Error: Bad value true for attribute novalidate on element form.
```

This is because this component was rendering

```
<form novalidate="true"...>
```

When the newer syntax for boolean attributes is to reference the attribute alone

```
<form novalidate .....>
```

Signed-off-by: Alistair Laing <aliuk2012@users.noreply.github.com>